### ISSUE TITLE
Compatibility with other selfhosted ChatGPT alternatives

### ISSUE THREAD

**Issue by UmutAlihan** [alaeddine-13/thinkgpt#15]
Hi, 

Your contribution to OS community is greatly appreciated. Thank you!

I am curious that whether this repo is only for OpenAI API?

Is it possible to use with Falcon-40B-Instruct model? If so how? Could you provide some help? 

Cheers,

**Comment by crrrr30** [comment]
I've been working on the same thing, and the best solution I found so far is to use [vLLM](https://github.com/vllm-project/vllm/) to host an OpenAI-like server and modify this repository to use VLLMOpenAI instead, calling that server.
